# conda env create -f environment.yml
name: birdy
channels:
  - birdhouse
  - conda-forge
  - defaults
dependencies:
  - six
  - openssl
  - lxml
  - owslib>=0.17
  - pathlib
  - click
  - jinja2
  - wrapt
  - funcsigs
  - boltons
  # optional
  - netcdf4
  # tests
  - pytest
  - flake8
  # sphinx for rtd
  - sphinx
  - pip:
    - sphinx-autoapi
